/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PropertyName } from "./PropertyName";
import { PropertyNameCountArgs } from "./PropertyNameCountArgs";
import { PropertyNameFindManyArgs } from "./PropertyNameFindManyArgs";
import { PropertyNameFindUniqueArgs } from "./PropertyNameFindUniqueArgs";
import { DeletePropertyNameArgs } from "./DeletePropertyNameArgs";
import { PropertyNameService } from "../propertyName.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => PropertyName)
export class PropertyNameResolverBase {
  constructor(
    protected readonly service: PropertyNameService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PropertyName",
    action: "read",
    possession: "any",
  })
  async _propertyNamesMeta(
    @graphql.Args() args: PropertyNameCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PropertyName])
  @nestAccessControl.UseRoles({
    resource: "PropertyName",
    action: "read",
    possession: "any",
  })
  async propertyNames(
    @graphql.Args() args: PropertyNameFindManyArgs
  ): Promise<PropertyName[]> {
    return this.service.propertyNames(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PropertyName, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PropertyName",
    action: "read",
    possession: "own",
  })
  async propertyName(
    @graphql.Args() args: PropertyNameFindUniqueArgs
  ): Promise<PropertyName | null> {
    const result = await this.service.propertyName(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PropertyName)
  @nestAccessControl.UseRoles({
    resource: "PropertyName",
    action: "delete",
    possession: "any",
  })
  async deletePropertyName(
    @graphql.Args() args: DeletePropertyNameArgs
  ): Promise<PropertyName | null> {
    try {
      return await this.service.deletePropertyName(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
